# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X github.com/crowdstrike/falcon-installer/internal/version.Version={{.Version}} -X github.com/crowdstrike/falcon-installer/internal/version.Commit={{.Commit}}'
    main: ./cmd/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - s390x
    ignore:
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: s390x
      - goos: darwin
        goarch: s390x

archives:
  - id: archives
    formats:
      - tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Os "darwin" }}macos-
      {{- else }}{{- .Os }}-{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip

  - id: binary
    formats:
      - binary
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Os "darwin" }}macos-
      {{- else }}{{- .Os }}-{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  disable: true
